import type { Plan } from '@/features/plans/types';

export const mockPlans: Plan[] = [
  {
    id: 'plan-1',
    title: 'Rooftop Jazz & Wine',
    description:
      'Small rooftop session with live jazz, wine tasting, and city lights. Perfect for meeting new people in a relaxed atmosphere.',
    location: 'Le Marais',
    coordinates: { lat: 48.8566, lng: 2.3622 },
    host: {
      name: 'Sophie',
      avatarUrl: 'https://picsum.photos/seed/sophie/200/200',
      verified: true,
    },
    startsAt: 'Starts in 1h',
    energy: 'low',
    tags: ['Jazz', 'Wine', 'Rooftop'],
    attendees: 14,
    maxAttendees: 20,
    matchPercentage: 94,
    genderRatio: { female: 60, male: 40 },
    price: 'moderate',
    ageRange: '25-30 y/o',
    imageUrl: 'https://picsum.photos/seed/jazz-rooftop/800/600',
    isHappeningNow: true,
    distance: '1.2km',
  },
  {
    id: 'plan-2',
    title: 'Underground Techno',
    description:
      'Warehouse-style techno night for people who want to dance until sunrise. Expect dark beats, strobe lights, and an unforgettable experience.',
    location: 'Kreuzberg',
    coordinates: { lat: 48.8530, lng: 2.3690 },
    host: {
      name: 'Max',
      avatarUrl: 'https://picsum.photos/seed/max/200/200',
      verified: true,
    },
    startsAt: '23:30',
    energy: 'high',
    tags: ['Techno', 'Late Night', 'Dancing'],
    attendees: 26,
    maxAttendees: 30,
    matchPercentage: 87,
    genderRatio: { female: 50, male: 50 },
    price: 'expensive',
    ageRange: '21-35 y/o',
    imageUrl: 'https://picsum.photos/seed/techno-warehouse/800/600',
    isHappeningNow: false,
    distance: '3.5km',
  },
  {
    id: 'plan-3',
    title: 'Late Night Food Run',
    description:
      'Street food walk with spontaneous stops and good conversation. We will explore the best late-night spots in Bastille.',
    location: 'Bastille',
    coordinates: { lat: 48.8545, lng: 2.3710 },
    host: {
      name: 'Elena',
      avatarUrl: 'https://picsum.photos/seed/elena/200/200',
      verified: false,
    },
    startsAt: '01:00',
    energy: 'medium',
    tags: ['Food', 'Casual', 'Social'],
    attendees: 8,
    maxAttendees: 12,
    matchPercentage: 78,
    genderRatio: { female: 55, male: 45 },
    price: 'cheap',
    ageRange: '22-28 y/o',
    imageUrl: 'https://picsum.photos/seed/food-run/800/600',
    isHappeningNow: false,
    distance: '2km',
  },
  {
    id: 'plan-4',
    title: 'Cocktail Masterclass',
    description:
      'Learn to make 3 classic cocktails with a professional mixologist. All ingredients included, plus light snacks.',
    location: 'Montmartre',
    coordinates: { lat: 48.8490, lng: 2.3430 },
    host: {
      name: 'Alexandre',
      avatarUrl: 'https://picsum.photos/seed/alex/200/200',
      verified: true,
    },
    startsAt: '19:00',
    energy: 'medium',
    tags: ['Cocktails', 'Class', 'Social'],
    attendees: 10,
    maxAttendees: 15,
    matchPercentage: 82,
    genderRatio: { female: 65, male: 35 },
    price: 'expensive',
    ageRange: '25-35 y/o',
    imageUrl: 'https://picsum.photos/seed/cocktails/800/600',
    isHappeningNow: false,
    distance: '4km',
  },
  {
    id: 'plan-5',
    title: 'Sunset Picnic',
    description:
      'Relaxed picnic by the Seine as the sun goes down. Bring your own drinks, we will provide snacks and blankets.',
    location: 'Seine River',
    coordinates: { lat: 48.8660, lng: 2.3800 },
    host: {
      name: 'Marie',
      avatarUrl: 'https://picsum.photos/seed/marie/200/200',
      verified: false,
    },
    startsAt: '18:30',
    energy: 'low',
    tags: ['Picnic', 'Sunset', 'Outdoors'],
    attendees: 18,
    maxAttendees: 25,
    matchPercentage: 91,
    genderRatio: { female: 70, male: 30 },
    price: 'cheap',
    ageRange: '20-30 y/o',
    imageUrl: 'https://picsum.photos/seed/sunset-picnic/800/600',
    isHappeningNow: false,
    distance: '0.8km',
  },
];
