import type { Plan } from '@/features/plans/types';

export const mockPlans: Plan[] = [
    {
        id: 'plan-1',
        title: 'Rooftop Jazz & Wine',
        description:
            'Small rooftop session with live jazz, wine tasting, and city lights. Perfect for meeting new people in a relaxed atmosphere.',
        location: 'Le Marais',
        coordinates: { lat: 48.8566, lng: 2.3622 },
        host: {
            id: 'host-1',
            name: 'Sophie',
            avatarUrl: 'https://picsum.photos/seed/sophie/200/200',
            verified: true,
            hostLevel: 'Ambassador',
            rating: 4.8,
        },
        startsAt: 'Starts in 1h',
        energy: 'low',
        activityType: 'drinks',
        tags: ['Jazz', 'Wine', 'Rooftop'],
        attendees: 14,
        maxAttendees: 20,
        price: 'moderate',
        ageRange: '25-30 y/o',
        approvalRequired: true,
        imageUrl: 'https://picsum.photos/seed/jazz-rooftop/800/600',
        isHappeningNow: true,
    },
    {
        id: 'plan-2',
        title: 'Underground Techno',
        description:
            'Warehouse-style techno night for people who want to dance until sunrise. Expect dark beats, strobe lights, and an unforgettable experience.',
        location: 'Kreuzberg',
        coordinates: { lat: 48.853, lng: 2.369 },
        host: {
            id: 'host-2',
            name: 'Max',
            avatarUrl: 'https://picsum.photos/seed/max/200/200',
            verified: true,
            hostLevel: 'Legend',
            rating: 4.9,
        },
        startsAt: '23:30',
        energy: 'high',
        activityType: 'party',
        tags: ['Techno', 'Late Night', 'Dancing'],
        attendees: 26,
        maxAttendees: 30,
        price: 'expensive',
        ageRange: '21-35 y/o',
        approvalRequired: false,
        imageUrl: 'https://picsum.photos/seed/techno-warehouse/800/600',
        isHappeningNow: false,
    },
    {
        id: 'plan-3',
        title: 'Late Night Food Run',
        description:
            'Street food walk with spontaneous stops and good conversation. We will explore the best late-night spots in Bastille.',
        location: 'Bastille',
        coordinates: { lat: 48.8545, lng: 2.371 },
        host: {
            id: 'host-3',
            name: 'Elena',
            avatarUrl: 'https://picsum.photos/seed/elena/200/200',
            verified: false,
            hostLevel: 'Newcomer',
            rating: 0,
        },
        startsAt: '01:00',
        energy: 'medium',
        activityType: 'food',
        tags: ['Food', 'Casual', 'Social'],
        attendees: 8,
        maxAttendees: 12,
        price: 'cheap',
        ageRange: '22-28 y/o',
        approvalRequired: true,
        imageUrl: 'https://picsum.photos/seed/food-run/800/600',
        isHappeningNow: false,
    },
    {
        id: 'plan-4',
        title: 'Cocktail Masterclass',
        description:
            'Learn to make 3 classic cocktails with a professional mixologist. All ingredients included, plus light snacks.',
        location: 'Montmartre',
        coordinates: { lat: 48.849, lng: 2.343 },
        host: {
            id: 'host-4',
            name: 'Alexandre',
            avatarUrl: 'https://picsum.photos/seed/alex/200/200',
            verified: true,
            hostLevel: 'Regular',
            rating: 4.5,
        },
        startsAt: '19:00',
        energy: 'medium',
        activityType: 'drinks',
        tags: ['Cocktails', 'Class', 'Social'],
        attendees: 10,
        maxAttendees: 15,
        price: 'expensive',
        ageRange: '25-35 y/o',
        approvalRequired: true,
        imageUrl: 'https://picsum.photos/seed/cocktails/800/600',
        isHappeningNow: false,
    },
    {
        id: 'plan-5',
        title: 'Sunset Picnic',
        description:
            'Relaxed picnic by the Seine as the sun goes down. Bring your own drinks, we will provide snacks and blankets.',
        location: 'Seine River',
        coordinates: { lat: 48.866, lng: 2.38 },
        host: {
            id: 'host-5',
            name: 'Marie',
            avatarUrl: 'https://picsum.photos/seed/marie/200/200',
            verified: false,
            hostLevel: 'Regular',
            rating: 4.0,
        },
        startsAt: '18:30',
        energy: 'low',
        activityType: 'food',
        tags: ['Picnic', 'Sunset', 'Outdoors'],
        attendees: 18,
        maxAttendees: 25,
        price: 'cheap',
        ageRange: '20-30 y/o',
        approvalRequired: false,
        imageUrl: 'https://picsum.photos/seed/sunset-picnic/800/600',
        isHappeningNow: false,
    },
];
