import { createTamagui, createTokens } from 'tamagui';

import { noctuaColors } from '@/lib/theme/tokens';

const tokens = createTokens({
  color: {
    background: noctuaColors.background,
    backgroundSoft: noctuaColors.surfaceSoft,
    surface: noctuaColors.surface,
    border: noctuaColors.border,
    text: noctuaColors.text,
    textMuted: noctuaColors.textMuted,
    primary: noctuaColors.primary,
    success: noctuaColors.success,
  },
  space: {
    0: 0,
    1: 4,
    2: 8,
    3: 12,
    4: 16,
    5: 20,
    6: 24,
    7: 32,
    true: 16,
  },
  size: {
    0: 0,
    1: 12,
    2: 14,
    3: 16,
    4: 18,
    5: 20,
    6: 24,
    7: 28,
    8: 32,
    true: 16,
  },
  radius: {
    0: 0,
    1: 6,
    2: 10,
    3: 14,
    4: 18,
    5: 24,
    6: 999,
    true: 10,
  },
  zIndex: {
    0: 0,
    1: 10,
    2: 50,
    3: 100,
    4: 1000,
    true: 1,
  },
});

export const tamaguiConfig = createTamagui({
  tokens,
  themes: {
    dark: {
      background: '$background',
      backgroundHover: '$backgroundSoft',
      backgroundPress: '$surface',
      backgroundFocus: '$surface',
      borderColor: '$border',
      borderColorHover: '$primary',
      borderColorPress: '$primary',
      borderColorFocus: '$primary',
      color: '$text',
      colorHover: '$text',
      colorPress: '$text',
      colorFocus: '$text',
      placeholderColor: '$textMuted',
      outlineColor: '$primary',
      shadowColor: '$border',
    },
    light: {
      background: '$background',
      backgroundHover: '$backgroundSoft',
      backgroundPress: '$surface',
      backgroundFocus: '$surface',
      borderColor: '$border',
      borderColorHover: '$primary',
      borderColorPress: '$primary',
      borderColorFocus: '$primary',
      color: '$text',
      colorHover: '$text',
      colorPress: '$text',
      colorFocus: '$text',
      placeholderColor: '$textMuted',
      outlineColor: '$primary',
      shadowColor: '$border',
    },
  },
  defaultTheme: 'dark',
});
